Script started on 2024-03-09 22:13:09-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="120" LINES="30"]
[?2004h]0;cmward@Collin-Ward: /mnt/c/Users/Aquad/Documents/Comp/Comp3500/Project3[01;32mcmward@Collin-Ward[00m:[01;34m/mnt/c/Users/Aquad/Documents/Comp/Comp3500/Project3[00m$ ./Collin_Ward
[?2004lbanner_id: 904158384
m: input the number of processes
4
n: input the number of types of resources
3
Max Matrix: input the value of each element left to right, top to bottom
7
5
3
3
2
2
9
0
2
2
2
2
Allocation Matrix: input the value of each element left to right, top to bottom
0
1
0
2
0
0
3
0
2
2
1
1
Available Vector: input the value of each element left to right
3
3
4
The system is safe
The safe sequence is:
1-->3-->0-->2 
A process start to request resources. The process number is: 
1
Each type resource requested by this proess
1
2
2
The system is safe
The safe sequence is:
1-->3-->0-->2 
Request approved!
Do you want to try again? Yes press y/Y, otherwise press any other key to quit
y
A process start to request resources. The process number is: 
0
Each type resource requested by this proess
7
4
3
Requested more than available, please re-try!
Requested more than available, please re-try!
Requested more than available, please re-try!
The system is not safe
Your request is declined!
Do you want to try again? Yes press y/Y, otherwise press any other key to quit
n
[?2004h]0;cmward@Collin-Ward: /mnt/c/Users/Aquad/Documents/Comp/Comp3500/Project3[01;32mcmward@Collin-Ward[00m:[01;34m/mnt/c/Users/Aquad/Documents/Comp/Comp3500/Project3[00m$ exit
[?2004lexit

Script done on 2024-03-09 22:15:39-06:00 [COMMAND_EXIT_CODE="0"]
